server:
  port: 7779

spring:
  application:
    name: transactions-server
  profiles:
    active: development
  datasource:
    url: jdbc:postgresql://transactions_db:5432/transactionsDb
    platform: postgres
    continue-on-error: true
    username: transactionsUser
    password: transactionsPasswd
  jpa:
    hibernate:
      ddl-auto: update
