server:
  port: 7780

spring:
  application:
    name: cards-server
  profiles:
    active: development
  datasource:
    url: jdbc:postgresql://localhost:5437/cardsDb
    platform: postgres
    continue-on-error: true
    username: cardsUser
    password: cardsPasswd
  jpa:
    hibernate:
      ddl-auto: update
