server:
  port: 7778

spring:
  application:
    name: users
  profiles:
    active: development
  jpa:
    hibernate:
      ddl-auto: update

users:
  datasource:
    url: jdbc:postgresql://localhost:5433/usersDb
    username: usersUser
    password: usersPasswd
    driver-class-name: org.postgresql.Driver
